File io
anthonymesa/Cwacos pull request #33
Opened 2021-04-09 02:02 UTC by Alan-Choi

Let me know if there are any issues.

2021-04-09 14:33 UTC, anthonymesa requested changes
Great work! I left some comments about implementing more try/catch's. The functions that throw exceptions will need to have "throws ExceptionOfSomeType" in their function declarations, and these function declarations will also need to be updated to match in the StorageAdapter.

2021-04-09 14:33 UTC, anthonymesa commented on src/main/java/LocalStorageTranslator.java
> +    private static Path getPath(String _fileName) {
lets implement a try catch here for InvalidPathException

2021-04-09 14:33 UTC, anthonymesa commented on src/main/java/DataStorage.java
>      public void save(ArrayList<String> _params, ArrayList<Entry> _input) {
Does this compile? Shouldn't there be a "throws" declaration in this function definition?

2021-04-09 14:33 UTC, anthonymesa commented on src/main/java/LocalStorageTranslator.java
>          } catch (IOException ex) {
If storing the file fails, lets throw an exception.

2021-04-09 14:33 UTC, anthonymesa commented on src/main/java/LocalStorageTranslator.java
>              }
again, lets catch any errors and throw an error

2021-04-09 16:02 UTC, Alan-Choi commented on src/main/java/DataStorage.java
>      public void save(ArrayList<String> _params, ArrayList<Entry> _input) {
It does compile and should run just fine, but I can put the declaration if you'd like.

2021-04-17 02:40 UTC, anthonymesa approved these changes

2021-04-17 02:40 UTC, merged