Intraday API Class
anthonymesa/Cwacos pull request #4
Opened 2021-02-26 16:09 UTC by mcleoar

The APIProgram class will call and store the Intraday JSON for the given stock name in an ArrayList of Entry objects. Entry is a supporting class whose objects hold the high, low, open, close, and volume of each interval given by the Intraday call.

2021-02-26 16:54 UTC, anthonymesa requested changes
This is a great start! I added some feedback in the request on things that we should do before merging. These changes will make it easier on us in the future if we want to extend our APIClass with more API calls (and in turn more methods). Keeps us from rewriting code unnecessarily

2021-02-26 16:54 UTC, anthonymesa commented on src/com/cwacos/APIClass.java
> +                    System.out.println(intraday.get(i).toString());
We should split the logic for making the API calls, and the logic for parsing the data into two different functions that each only have one job. This way we can call parseEntries(JSON data) inside getIntradayInfo() to parse and populate the entries with relevant info. A couple reasons for this: One, if we want to pull full day data as well as intraday data, we don't have to rewrite the parsing code, and two, if any of the JSON keys such as "1. open" changes in the API, we only have to update one function rather than every function that makes a request to the API.

2021-02-26 16:54 UTC, anthonymesa commented on src/com/cwacos/APIClass.java
> +}
Again, we want to return that ArrayList.

2021-02-26 16:54 UTC, anthonymesa commented on src/com/cwacos/APIClass.java
> +    public static void getIntradayInfo(String _stock){
This function should return the ArrayList of Entries

2021-02-26 16:54 UTC, anthonymesa commented on src/com/cwacos/APIClass.java
> +        String baseUrl = "https://www.alphavantage.co/query?";
Lets make this a class level static final so that we don't have to repeat the url in future functions

2021-02-26 16:54 UTC, anthonymesa commented on src/com/cwacos/APIClass.java
> +        String apiKey = "MO9QU9JAPBBPX5T7";
This key should also be a class level static final for the same reason as ln18.

2021-02-26 16:54 UTC, anthonymesa commented on src/com/cwacos/APIClass.java
> +                con.disconnect();
This may be a little bit in the weeds, but we may want to make a connection function like getContent so that we dont have to re-write the connection logic in future API calls. This way getIntradayInfo would just create the relevant url string that the API function needs, pass that to a getContent method that returns the content, and then the rest of getIntradayInfo would turn that content into a JSONObject that then gets passed to parseEntries(JSONObject) (see below), which would then return the entries that need to be returned from getIntradayInfo.

2021-02-26 17:00 UTC, mcleoar commented
Thank you for the great feedback Anthony! I agree I definitely need to reformat things and improve reusability. I will start with separating the the logic into different methods and resolve the things you mentioned as I go.

2021-03-12 04:46 UTC, mcleoar commented
Changes were made and ready for review. Let me know if you see anything else I could do.

2021-03-17 05:46 UTC, mcleoar commented
My errors were not being detected before so the original code was not runnable. It has been fixed.

2021-03-17 23:17 UTC, merged